### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by djjul** [pantunes/xtcryptosignals#275]
Hello.

I am testing Xtcryptosignals but I have several errors, one is when I go to the server IP 192.168.1.3:8000 I have errors that do not appear if I go to 127.0.0.1:8000 I tried to configure it in many ways but something escapes me:

Access to XMLHttpRequest at 'http://127.0.0.1:5001/socket.io/?EIO=4&transport=polling&t=NfN-yKD' from origin 'http://192.168.1.3:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
127.0.0.1:5001/socket.io/?EIO=4&transport=polling&t=NfN-yKD:1 Failed to load resource: net::ERR_FAILED

On the other hand, when I put the telegram configuration in server.dev.env, I never received a message.

Thanks and great job

**Comment by pantunes** [comment]
Hi @djjul 

Regarding the CORS issue is related with `flask_socketio`, make sure in your `client.*.env` you have the constant `SOCKET_BASE_URL` set correctly.
For example:
<img width="653" alt="Screenshot 2021-07-01 at 00 37 39" src="https://user-images.githubusercontent.com/6731272/124040090-2b842a80-d9fc-11eb-82a3-e9d39e81c93a.png">

And in your `server.*.env` you have the constant `CORS_ALLOWED_ORIGINS` set correctly such:
<img width="570" alt="Screenshot 2021-07-01 at 00 38 43" src="https://user-images.githubusercontent.com/6731272/124040190-52426100-d9fc-11eb-928b-2365f823a48d.png">
As far as I can see from example you should add `http://192.168.1.3:8000` here.

Regarding Telegram issue, did you create a Telegram bot previously and set the values of `TELEGRAM_BOT_TOKEN` and `TELEGRAM_GROUP_CHAT_ID`? If all looks good, these notifications are fired from the Tasks service. Do you have Can you check the logs here to see what is happening? Did you add notifications rules?

Thanks for your feedback!

**Comment by pantunes** [comment]
Hi @djjul ! Could you make it? 
if all is good let me know so i can close this issue, if not let me know about your progress.
Cheers

**Comment by pantunes** [comment]
19 days passed my last question - closing the issue
